### ISSUE TITLE
大佬！我install ok 之后run dev 编译报错了呀。。

### ISSUE THREAD

**Issue by xxbld** [aifang/ts_vue_esri#2]

**Comment by aifang** [comment]
这是我在选型的时候用的，太久了忘了到哪了，说说大概要注意的事情
1.dojo和vue，react一起用，必须用esriloader来引用dojo模块，
2.vue用typescript来写，体验并不好，问题也很多
3.vue 和react用 webpack打包，dojo不行，只能用gulp象征性压缩一下，如果你能深入了解dojo就知道怎么回事了
4.若dojo作为主框架，则完全享受不到webpack带来的便利
